version: '3.1'

services:
  mongodb:
    image: mongo
    container_name: mongodatabase
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass